-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 16:34:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema outsideFood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema outsideFood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `outsideFood` DEFAULT CHARACTER SET utf8 ;
USE `outsideFood` ;

-- -----------------------------------------------------
-- Table `outsideFood`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`cidades` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`eventos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `organizador` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `cidades_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_cidades1_idx` (`cidades_id` ASC),
  CONSTRAINT `fk_eventos_cidades1`
    FOREIGN KEY (`cidades_id`)
    REFERENCES `outsideFood`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`edicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`edicoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `capacidade` INT NOT NULL,
  `lotacao` INT NOT NULL,
  `eventos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_edicoes_eventos1_idx` (`eventos_id` ASC),
  CONSTRAINT `fk_edicoes_eventos1`
    FOREIGN KEY (`eventos_id`)
    REFERENCES `outsideFood`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`espacos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`espacos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `aluguel` DOUBLE NOT NULL,
  `metragem` DOUBLE NOT NULL,
  `benfeitoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`servicos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` TINYINT NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `salario` DOUBLE NOT NULL,
  `espacos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servicos_espacos1_idx` (`espacos_id` ASC),
  CONSTRAINT `fk_servicos_espacos1`
    FOREIGN KEY (`espacos_id`)
    REFERENCES `outsideFood`.`espacos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`pratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`pratos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`funcionarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` TINYINT NOT NULL,
  `servicos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionarios_servicos1_idx` (`servicos_id` ASC),
  CONSTRAINT `fk_funcionarios_servicos1`
    FOREIGN KEY (`servicos_id`)
    REFERENCES `outsideFood`.`servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`ingredientes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`culinaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`culinaria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_culinaria` VARCHAR(45) NOT NULL,
  `tempo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`login` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`locais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`locais` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cidades_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locais_cidades_idx` (`cidades_id` ASC),
  CONSTRAINT `fk_locais_cidades`
    FOREIGN KEY (`cidades_id`)
    REFERENCES `outsideFood`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`pratos_has_ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`pratos_has_ingredientes` (
  `pratos_id` INT UNSIGNED NOT NULL,
  `ingredientes_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pratos_id`, `ingredientes_id`),
  INDEX `fk_pratos_has_ingredientes_ingredientes1_idx` (`ingredientes_id` ASC),
  INDEX `fk_pratos_has_ingredientes_pratos1_idx` (`pratos_id` ASC),
  CONSTRAINT `fk_pratos_has_ingredientes_pratos1`
    FOREIGN KEY (`pratos_id`)
    REFERENCES `outsideFood`.`pratos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pratos_has_ingredientes_ingredientes1`
    FOREIGN KEY (`ingredientes_id`)
    REFERENCES `outsideFood`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`servicos_has_pratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`servicos_has_pratos` (
  `servicos_id` INT UNSIGNED NOT NULL,
  `pratos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`servicos_id`, `pratos_id`),
  INDEX `fk_servicos_has_pratos_pratos1_idx` (`pratos_id` ASC),
  INDEX `fk_servicos_has_pratos_servicos1_idx` (`servicos_id` ASC),
  CONSTRAINT `fk_servicos_has_pratos_servicos1`
    FOREIGN KEY (`servicos_id`)
    REFERENCES `outsideFood`.`servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_has_pratos_pratos1`
    FOREIGN KEY (`pratos_id`)
    REFERENCES `outsideFood`.`pratos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`vendas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `servicos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendas_servicos1_idx` (`servicos_id` ASC),
  CONSTRAINT `fk_vendas_servicos1`
    FOREIGN KEY (`servicos_id`)
    REFERENCES `outsideFood`.`servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`funcionarios_has_culinaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`funcionarios_has_culinaria` (
  `funcionarios_id` INT UNSIGNED NOT NULL,
  `culinaria_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`funcionarios_id`, `culinaria_id`),
  INDEX `fk_funcionarios_has_culinaria_culinaria1_idx` (`culinaria_id` ASC),
  INDEX `fk_funcionarios_has_culinaria_funcionarios1_idx` (`funcionarios_id` ASC),
  CONSTRAINT `fk_funcionarios_has_culinaria_funcionarios1`
    FOREIGN KEY (`funcionarios_id`)
    REFERENCES `outsideFood`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarios_has_culinaria_culinaria1`
    FOREIGN KEY (`culinaria_id`)
    REFERENCES `outsideFood`.`culinaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `outsideFood`.`edicoes_has_espacos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `outsideFood`.`edicoes_has_espacos` (
  `edicoes_id` INT UNSIGNED NOT NULL,
  `espacos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`edicoes_id`, `espacos_id`),
  INDEX `fk_edicoes_has_espacos_espacos1_idx` (`espacos_id` ASC),
  INDEX `fk_edicoes_has_espacos_edicoes1_idx` (`edicoes_id` ASC),
  CONSTRAINT `fk_edicoes_has_espacos_edicoes1`
    FOREIGN KEY (`edicoes_id`)
    REFERENCES `outsideFood`.`edicoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_edicoes_has_espacos_espacos1`
    FOREIGN KEY (`espacos_id`)
    REFERENCES `outsideFood`.`espacos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
